### ISSUE TITLE
404 for reading contributing file

### ISSUE THREAD

**Issue by mendoc** [JoseDeFreitas/thisisme#11]
**Describe the bug**
When we click on contribute link, it shows a 404 page.

**To Reproduce**
1. Go to https://thisisme.vercel.app/
2. Scroll down to footer
3. Click on contribute link

**Expected behavior**
When you click on the contribution link, the contribution file will be displayed for reading.

**Screenshots**
https://pasteboard.co/Ju59mqb.png

**Desktop or Smartphone (please complete the following information):**
 - Device: Laptop
 - OS: Ubuntu 16.04
 - Browser: Brave
 - Version: 1.12.112

**Additional context**
None

**Comment by mendoc** [comment]
@JoseDeFreitas can you assign me to this to fix the link ?

**Comment by mendoc** [comment]
I would also like to change the name of the master branch in footer links to put "main". I think it's in the same issue.

**Comment by JoseDeFreitas** [comment]
Hello @mendoc! I'm so sorry you are having that issue. It's already fixed in the latest version, but the version that is currently deployed ([thisisme.vercel.app](https://thisisme.vercel.app)) is an old version and has some bugs and incorrect functionalities. To see the latest changes, clone the repository and run `npm start`. I know this may be annoying instead of just opening the link, but when the new version comes out it will be available in the link and in production. As this is an issue with an old version of the webapp, I'm closing this issue. Feel free to reopen it if you have something to tell me. Thank you and sorry.
