### ISSUE TITLE
Result doesn't show all images

### ISSUE THREAD

**Issue by Tekipeps** [JoseDeFreitas/thisisme#14]
**Describe the bug**
I put some data in the Programming, Technologies and Personal sections but only Technologies appear in the result

**Expected behavior**
All Images are meant to appear in the result page?

Also are there any ways I can contribute to this project?

**Comment by JoseDeFreitas** [comment]
Hello @Tekipeps! You're right. That's a bug the web app is facing right now. It's happening because, as the system is using the localStorage to save and then retrieve the images from every section in the Result section, I could not figure out how to apply properties to add the images next to the other and below to the other. If a section's inputs are not filled up, the image should just not show up in the Result section. An example of how I want it is this: https://imgur.com/xGEkRWl

And yes, **you can contribute**! There're actually some [issues opened](https://github.com/JoseDeFreitas/thisisme/issues) about contributing. The contributions on this repository count for the Hacktoberfest 2020 event. If you would want to contribute just mention me and tell me so I can assign you. Thank you for opening this issue!

**Comment by leonyangela** [comment]
Hello, can I help to solve some issues? If so, can you please assign me a task, Thank you

**Comment by JoseDeFreitas** [comment]
Hello @leonyangela! There're some [issues opened](https://github.com/JoseDeFreitas/thisisme/issues) right now. This issue is about a problem with the layout of the images in the "Result" section. It's better if you see the code by yourself so you can understand what's happening, but basically, all images that you generate through the other sections are colliding with each other and being one on top of the other. In fact, all the images are there, but they're above the other one so it looks like there's just one. If you want, I can assign you to this issue.

**Comment by Tekipeps** [comment]
I will like to work on this @JoseDeFreitas

**Comment by JoseDeFreitas** [comment]
Okay! I just assigned you @Tekipeps to this issue. If you have any questions mention me and tell me. Thank you a lot!

**Comment by Tekipeps** [comment]
I noticed the variable names are quite long and no comments to that explain pieces of code

**Comment by JoseDeFreitas** [comment]
@Tekipeps you're right. As I said earlier, the code is confusing. **The explanation I give below affects to all the sections.** Education, Job, and Certificates are the hardest-to-understand sections because they have 2-3 forms with 3 inputs each. Sections like Personal, Programming, and Education are not so complex. Below I made a table that you may find useful about the variables:

```
educationNameValueStored1 = values with this syntax are the given names that are saved in the localStorage and then used in the other variables (inside the `<text>` and `<tspan>` tags) to be printed in the image.
setValueEducationName1 = these variables work as functions (useState hook) for adding the text value from the inputs to the localStorage.
valueChangeEducationTitle1 = used only in the `onChange` property inside every `input` tag.
valueEducationName1 = variables like this are defined in the useState hook for holding the value that is in the localStorage and used several times in the conditionals.
imgHeight = sets the height of the image depending on the values.
educationInnerCard1 = creates the inner card (only in Education, Job, and Certificates sections.)
educationNameText1 = defines the texts (these variables are the ones passed directly into the svgImage variables.) They use the other variables to control the positioning.

In the variables, you can see names like "education", "Job", "Personal", etc. This means they correspond to the Education, Job, and Personal sections (for example using these sections.)
The numbers next to the variables are used to indicate which form they correspond (only for Education, Job, and Certificates sections.)
```

Writing about the comments, it should have some comments explaining what does which thing. If you can add some comments, that would be great.
Briefly explaining, the first chink of code (something like this):
```js
const [valueEducationYears1, setValueEducationYears1] = useLocalStorage(
        'educationYearsValueStored1'
    );
    const valueChangeEducationYears1 = event => setValueEducationYears1(event.target.value);
```
is used to save the values into the localStorage, for future retrieval when printing them into the image. The code below that just tests the positioning of some text depending on if the text that is above is no or is present (if it's not, the text that is below should go to the position of the other one. If it's present, the text should stay where it is.) This process is made several times for every text (every input.) These variables are then used in the image to print the text with the proper position (variables use conditionals.)

Still is confusing, so let me know if you want more explanation. Sorry for this.

**Comment by Tekipeps** [comment]
![image](https://user-images.githubusercontent.com/45674928/95248857-cb1ae080-080f-11eb-8dbe-2a53234f3a62.png)
for this i think its more appropriate to use `JSON.stringify()`
@JoseDeFreitas

**Comment by Tekipeps** [comment]
> ![image](https://user-images.githubusercontent.com/45674928/95248857-cb1ae080-080f-11eb-8dbe-2a53234f3a62.png)
> for this i think its more appropriate to use `String()`
> @JoseDeFreitas

I did more research ignore this comment

**Comment by Tekipeps** [comment]
> Hello @Tekipeps! You're right. That's a bug the web app is facing right now. It's happening because, as the system is using the localStorage to save and then retrieve the images from every section in the Result section, I could not figure out how to apply properties to add the images next to the other and below to the other. If a section's inputs are not filled up, the image should just not show up in the Result section. An example of how I want it is this: https://imgur.com/xGEkRWl
> 
> And yes, **you can contribute**! There're actually some [issues opened](https://github.com/JoseDeFreitas/thisisme/issues) about contributing. The contributions on this repository count for the Hacktoberfest 2020 event. If you would want to contribute just mention me and tell me so I can assign you. Thank you for opening this issue!

 I have understood what is causing this and I am currently working on a fix.
The issue is that they all have the same x and y at 0.5 to they start at the same point in the svg Image

**Comment by JoseDeFreitas** [comment]
@Tekipeps Yes, that's the issue the web app is having. As previously said, images collapse with each other on the Result page. Thank you for working on it!

**Comment by JoseDeFreitas** [comment]
Now the "Result" section shows all the images. I'm closing this issue. Thank you!
