### ISSUE TITLE
Add/Update button is not working

### ISSUE THREAD

**Issue by nischalsoni** [JoseDeFreitas/thisisme#9]
**Describe the bug**
Whenever I fill in my information at any page and hit Add/Update button, nothing happens. The info is not getting stored, nor any further activity happens.

**Expected behaviour**
It is supposed to store the info and move on to the next part(next page for taking in new info) but nothing happens.

**Screenshots**
None

**Desktop or Smartphone (please complete the following information):**
 - Device: Laptop
 - OS: Windows
 - Browser: Chrome
 - Version: No idea

**Comment by JoseDeFreitas** [comment]
Hello @nischalsoni! I'm so sorry for this issue. The deploy that is currently up running is one old version of the webapp. To see the most recent version you have to clone the repository and run `npm start` to see the new version (which is working). I know it's kind of annoying to do that instead of just going to the link, but whenever the new changes are made the link will have the latest updates (production). As this is already solved I'm closing this issue, but feel free to reopen it to tell me something else if you want. Thank you.
